/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.ucsb.multisnake.server;

public class App {
    public static void main(String[] args) {
        Server s = new Server();
        s.init();

    }
}
